from __future__ import annotations

from typing import Any

ENDPOINTS = {
    "health": "/health",
    "diagnostics": "/diagnostics",
    "discover": "/discover",
    "entities": "/entities",
    "state": "/state",
    "config": "/config",
    "config_sync": "/config/sync",
    "deconfigure": "/deconfigure",
    "ui_config": "/ui-config",
    "events": "/events",
    "command": "/command",
    "telemetry_example": "/telemetry/example",
    "manifest": "/manifest.json",
    "behaviors": "/behaviors.json",
    "manifest_static": "/manifest.static.json",
    "behaviors_static": "/behaviors.static.json",
}

REQUIRED_ENDPOINTS = ["health", "entities", "command", "config", "ui_config"]

CAPABILITIES: dict[str, dict[str, Any]] = {
    "connected": {"kind": "sensor", "unit": "bool"},
    "power": {"kind": "sensor", "unit": "bool"},
    "latency_ms": {"kind": "sensor", "unit": "ms"},
    "dp_count": {"kind": "sensor", "unit": "count"},
    "protocol_version": {"kind": "sensor", "unit": "string"},
    "current_ma": {"kind": "sensor", "unit": "mA"},
    "power_w": {"kind": "sensor", "unit": "W"},
    "voltage_v": {"kind": "sensor", "unit": "V"},
    "mode": {"kind": "sensor", "unit": "string"},
    "brightness_percent": {"kind": "sensor", "unit": "%"},
    "color_temp_percent": {"kind": "sensor", "unit": "%"},
    "color_value": {"kind": "sensor", "unit": "string"},
    "fan_speed_percent": {"kind": "sensor", "unit": "%"},
    "oscillating": {"kind": "sensor", "unit": "bool"},
    "position_percent": {"kind": "sensor", "unit": "%"},
    "motion_state": {"kind": "sensor", "unit": "string"},
    "temperature_c": {"kind": "sensor", "unit": "C"},
    "target_temperature_c": {"kind": "sensor", "unit": "C"},
    "humidity_percent": {"kind": "sensor", "unit": "%"},
    "target_humidity_percent": {"kind": "sensor", "unit": "%"},
    "air_quality_index": {"kind": "sensor", "unit": "AQI"},
    "refresh": {"kind": "action"},
    "turn_on": {"kind": "action"},
    "turn_off": {"kind": "action"},
    "set_dp": {"kind": "action"},
    "set_brightness": {"kind": "action"},
    "set_color_temp": {"kind": "action"},
    "set_color_rgb": {"kind": "action"},
    "set_mode": {"kind": "action"},
    "set_fan_speed": {"kind": "action"},
    "set_oscillate": {"kind": "action"},
    "open_cover": {"kind": "action"},
    "close_cover": {"kind": "action"},
    "stop_cover": {"kind": "action"},
    "set_cover_position": {"kind": "action"},
    "set_temperature": {"kind": "action"},
    "set_humidity": {"kind": "action"},
}

COMMANDS: dict[str, dict[str, Any]] = {
    "refresh": {
        "description": "Refresh the latest local Tuya device state.",
        "timeout_ms": 5000,
    },
    "turn_on": {
        "description": "Turn the Tuya device on.",
        "timeout_ms": 5000,
    },
    "turn_off": {
        "description": "Turn the Tuya device off.",
        "timeout_ms": 5000,
    },
    "set_dp": {
        "description": "Set a raw Tuya data point value.",
        "timeout_ms": 5000,
        "args_schema": {
            "dp": {
                "type": "string",
                "label": "Data Point",
                "description": "Tuya DPS key, for example 1 or 20.",
                "required": True,
            },
            "value": {
                "type": "string",
                "label": "Value",
                "description": "JSON-ish scalar or string value to send to the device.",
                "required": True,
            },
        },
    },
    "set_brightness": {
        "description": "Set a Tuya light brightness percentage.",
        "timeout_ms": 5000,
        "args_schema": {
            "brightness": {
                "type": "number",
                "label": "Brightness Percent",
                "description": "Brightness percentage from 0 to 100.",
                "required": True,
                "minimum": 0,
                "maximum": 100,
                "step": 1,
                "unit": "%",
            }
        },
    },
    "set_color_temp": {
        "description": "Set a Tuya light color temperature percentage.",
        "timeout_ms": 5000,
        "args_schema": {
            "color_temp": {
                "type": "number",
                "label": "Color Temperature Percent",
                "description": "Color temperature percentage from 0 to 100.",
                "required": True,
                "minimum": 0,
                "maximum": 100,
                "step": 1,
                "unit": "%",
            }
        },
    },
    "set_color_rgb": {
        "description": "Set a Tuya light RGB color.",
        "timeout_ms": 5000,
        "args_schema": {
            "r": {
                "type": "number",
                "label": "Red",
                "required": True,
                "minimum": 0,
                "maximum": 255,
                "step": 1,
            },
            "g": {
                "type": "number",
                "label": "Green",
                "required": True,
                "minimum": 0,
                "maximum": 255,
                "step": 1,
            },
            "b": {
                "type": "number",
                "label": "Blue",
                "required": True,
                "minimum": 0,
                "maximum": 255,
                "step": 1,
            },
        },
    },
    "set_mode": {
        "description": "Set a Tuya light, fan, climate, humidifier, or air purifier mode.",
        "timeout_ms": 5000,
        "args_schema": {
            "mode": {
                "type": "string",
                "label": "Mode",
                "description": "Typical light modes are white, colour, scene, or music. Fan, climate, humidifier, and air purifier modes depend on the device and often include values like normal, sleep, auto, manual, heat, cool, eco, mist, low, medium, high, or off.",
                "required": True,
                "options": [
                    "white",
                    "colour",
                    "scene",
                    "music",
                    "normal",
                    "sleep",
                    "nature",
                    "auto",
                    "manual",
                    "heat",
                    "cool",
                    "eco",
                    "off",
                    "mist",
                    "low",
                    "medium",
                    "high",
                ],
            }
        },
    },
    "set_fan_speed": {
        "description": "Set a Tuya fan or air purifier speed percentage.",
        "timeout_ms": 5000,
        "args_schema": {
            "speed": {
                "type": "number",
                "label": "Fan Speed Percent",
                "description": "Requested fan speed from 0 to 100 percent.",
                "required": True,
                "minimum": 0,
                "maximum": 100,
                "step": 1,
                "unit": "%",
            }
        },
    },
    "set_oscillate": {
        "description": "Enable or disable Tuya fan oscillation.",
        "timeout_ms": 5000,
        "args_schema": {
            "oscillating": {"type": "boolean", "label": "Oscillating", "required": True}
        },
    },
    "open_cover": {
        "description": "Open a Tuya curtain, blind, or shade.",
        "timeout_ms": 5000,
    },
    "close_cover": {
        "description": "Close a Tuya curtain, blind, or shade.",
        "timeout_ms": 5000,
    },
    "stop_cover": {
        "description": "Stop a moving Tuya curtain, blind, or shade.",
        "timeout_ms": 5000,
    },
    "set_cover_position": {
        "description": "Set a Tuya cover position percentage.",
        "timeout_ms": 5000,
        "args_schema": {
            "position": {
                "type": "number",
                "label": "Position Percent",
                "description": "Requested cover position from 0 to 100 percent.",
                "required": True,
                "minimum": 0,
                "maximum": 100,
                "step": 1,
                "unit": "%",
            }
        },
    },
    "set_temperature": {
        "description": "Set a Tuya climate target temperature in Celsius.",
        "timeout_ms": 5000,
        "args_schema": {
            "temperature_c": {
                "type": "number",
                "label": "Target Temperature °C",
                "description": "Requested target temperature in degrees Celsius.",
                "required": True,
                "minimum": 5,
                "maximum": 35,
                "step": 0.5,
                "unit": "C",
            }
        },
    },
    "set_humidity": {
        "description": "Set a Tuya humidifier target humidity percentage.",
        "timeout_ms": 5000,
        "args_schema": {
            "humidity_percent": {
                "type": "number",
                "label": "Target Humidity Percent",
                "description": "Requested target humidity percentage from 0 to 100.",
                "required": True,
                "minimum": 0,
                "maximum": 100,
                "step": 1,
                "unit": "%",
            }
        },
    },
}

PLUG_ENTITY_CAPABILITIES = [
    "connected",
    "power",
    "latency_ms",
    "dp_count",
    "protocol_version",
    "current_ma",
    "power_w",
    "voltage_v",
    "refresh",
    "turn_on",
    "turn_off",
    "set_dp",
]

LIGHT_ENTITY_CAPABILITIES = [
    "connected",
    "power",
    "latency_ms",
    "dp_count",
    "protocol_version",
    "mode",
    "brightness_percent",
    "color_temp_percent",
    "color_value",
    "refresh",
    "turn_on",
    "turn_off",
    "set_brightness",
    "set_color_temp",
    "set_color_rgb",
    "set_mode",
    "set_dp",
]

FAN_ENTITY_CAPABILITIES = [
    "connected",
    "power",
    "latency_ms",
    "dp_count",
    "protocol_version",
    "mode",
    "fan_speed_percent",
    "oscillating",
    "refresh",
    "turn_on",
    "turn_off",
    "set_fan_speed",
    "set_oscillate",
    "set_mode",
    "set_dp",
]

COVER_ENTITY_CAPABILITIES = [
    "connected",
    "latency_ms",
    "dp_count",
    "protocol_version",
    "position_percent",
    "motion_state",
    "refresh",
    "open_cover",
    "close_cover",
    "stop_cover",
    "set_cover_position",
    "set_dp",
]

CLIMATE_ENTITY_CAPABILITIES = [
    "connected",
    "power",
    "latency_ms",
    "dp_count",
    "protocol_version",
    "mode",
    "temperature_c",
    "target_temperature_c",
    "refresh",
    "turn_on",
    "turn_off",
    "set_temperature",
    "set_mode",
    "set_dp",
]

HUMIDIFIER_ENTITY_CAPABILITIES = [
    "connected",
    "power",
    "latency_ms",
    "dp_count",
    "protocol_version",
    "mode",
    "humidity_percent",
    "target_humidity_percent",
    "refresh",
    "turn_on",
    "turn_off",
    "set_humidity",
    "set_mode",
    "set_dp",
]

AIR_PURIFIER_ENTITY_CAPABILITIES = [
    "connected",
    "power",
    "latency_ms",
    "dp_count",
    "protocol_version",
    "mode",
    "fan_speed_percent",
    "air_quality_index",
    "refresh",
    "turn_on",
    "turn_off",
    "set_fan_speed",
    "set_mode",
    "set_dp",
]

SWITCH_ENTITY_CAPABILITIES = [
    "connected",
    "power",
    "latency_ms",
    "dp_count",
    "protocol_version",
    "refresh",
    "turn_on",
    "turn_off",
    "set_dp",
]

CONFIG_SCHEMA: dict[str, Any] = {
    "schema": {
        "title": "PiPhi Network Tuya Setup",
        "type": "object",
        "required": ["host", "tuya_device_id", "local_key"],
        "properties": {
            "host": {
                "type": "string",
                "title": "Device IP / Host",
                "description": "LAN IP address reported by TinyTuya discovery or assigned manually.",
            },
            "tuya_device_id": {
                "type": "string",
                "title": "Tuya Device ID",
                "description": "Vendor device id returned by TinyTuya LAN or cloud discovery.",
            },
            "local_key": {
                "type": "string",
                "title": "Tuya Local Key",
                "description": "Required for local LAN control. Discovery cannot infer this value.",
            },
            "alias": {
                "type": "string",
                "title": "Alias",
                "description": "Friendly display name. Discovery usually seeds this from the Tuya product or device name.",
            },
            "device_type": {
                "type": "string",
                "title": "Device Type",
                "default": "plug",
                "enum": [
                    "plug",
                    "switch",
                    "light",
                    "fan",
                    "cover",
                    "climate",
                    "humidifier",
                    "air_purifier",
                    "device",
                ],
                "description": "Can be prefilled from discovery using Tuya category, DPS structure, and product-name heuristics.",
            },
            "version": {
                "type": "string",
                "title": "Protocol Version",
                "default": "3.3",
                "description": "TinyTuya protocol version such as 3.3, 3.4, or 3.5. Discovery will prefill this when scan results include a version.",
            },
            "switch": {
                "type": "integer",
                "title": "Primary Switch DP",
                "default": 1,
                "minimum": 1,
                "description": "Primary power datapoint. Discovery will suggest this from the first or most likely power DP, especially for multi-switch devices.",
            },
            "fan_speed_dp": {
                "type": "integer",
                "title": "Fan Speed DP",
                "default": 3,
                "minimum": 1,
                "description": "Optional fan speed datapoint override. Common values are 3 or 4.",
            },
            "fan_speed_max": {
                "type": "integer",
                "title": "Fan Speed Max",
                "default": 3,
                "minimum": 1,
                "description": "Maximum raw fan speed value used to map 0-100% requests to the device scale.",
            },
            "fan_oscillate_dp": {
                "type": "integer",
                "title": "Fan Oscillate DP",
                "minimum": 1,
                "description": "Optional oscillation datapoint override for Tuya fans.",
            },
            "fan_mode_dp": {
                "type": "integer",
                "title": "Fan Mode DP",
                "minimum": 1,
                "description": "Optional mode datapoint override for Tuya fans.",
            },
            "cover_control_dp": {
                "type": "integer",
                "title": "Cover Control DP",
                "default": 1,
                "minimum": 1,
                "description": "Datapoint used for open/close/stop commands on curtains, shades, or blinds.",
            },
            "cover_position_dp": {
                "type": "integer",
                "title": "Cover Position DP",
                "minimum": 1,
                "description": "Optional datapoint used for cover position percentages.",
            },
            "climate_target_temp_dp": {
                "type": "integer",
                "title": "Climate Target Temperature DP",
                "default": 16,
                "minimum": 1,
                "description": "Datapoint used for thermostat target temperature values.",
            },
            "climate_current_temp_dp": {
                "type": "integer",
                "title": "Climate Current Temperature DP",
                "minimum": 1,
                "description": "Optional datapoint used for thermostat current temperature readings.",
            },
            "climate_mode_dp": {
                "type": "integer",
                "title": "Climate Mode DP",
                "minimum": 1,
                "description": "Optional datapoint used for thermostat mode values like auto, manual, heat, or cool.",
            },
            "climate_temp_scale": {
                "type": "number",
                "title": "Climate Temperature Scale",
                "default": 1.0,
                "exclusiveMinimum": 0,
                "description": "Divisor applied to raw thermostat temperature values. Common values are 1 or 10.",
            },
            "humidifier_target_humidity_dp": {
                "type": "integer",
                "title": "Humidifier Target Humidity DP",
                "default": 103,
                "minimum": 1,
                "description": "Datapoint used for humidifier target humidity values.",
            },
            "humidifier_current_humidity_dp": {
                "type": "integer",
                "minimum": 1,
                "title": "Humidifier Current Humidity DP",
                "description": "Optional datapoint used for humidifier current humidity readings.",
            },
            "humidifier_mode_dp": {
                "type": "integer",
                "title": "Humidifier Mode DP",
                "minimum": 1,
                "description": "Optional datapoint used for humidifier mode values like auto, low, medium, high, or mist.",
            },
            "humidifier_humidity_scale": {
                "type": "number",
                "title": "Humidifier Humidity Scale",
                "default": 1.0,
                "exclusiveMinimum": 0,
                "description": "Divisor applied to raw humidifier humidity values. Common values are 1 or 10.",
            },
            "purifier_speed_dp": {
                "type": "integer",
                "title": "Air Purifier Speed DP",
                "default": 4,
                "minimum": 1,
                "description": "Optional datapoint override for air purifier fan speed or level control.",
            },
            "purifier_speed_max": {
                "type": "integer",
                "title": "Air Purifier Speed Max",
                "default": 3,
                "minimum": 1,
                "description": "Maximum raw speed value used to map 0-100% purifier speed requests to the device scale.",
            },
            "purifier_mode_dp": {
                "type": "integer",
                "title": "Air Purifier Mode DP",
                "minimum": 1,
                "description": "Optional datapoint used for purifier mode values like auto, sleep, or manual.",
            },
            "purifier_aqi_dp": {
                "type": "integer",
                "title": "Air Purifier AQI DP",
                "minimum": 1,
                "description": "Optional datapoint used for air quality readings such as AQI or PM-style indicator values.",
            },
            "purifier_aqi_scale": {
                "type": "number",
                "title": "Air Purifier AQI Scale",
                "default": 1.0,
                "exclusiveMinimum": 0,
                "description": "Divisor applied to raw air quality values. Common values are 1 or 10.",
            },
            "poll_interval_seconds": {
                "type": "integer",
                "title": "Poll Interval Seconds",
                "default": 60,
                "minimum": 10,
                "description": "Background polling interval for the configured Tuya device.",
            },
            "api_region": {
                "type": "string",
                "title": "Tuya Cloud API Region",
                "description": "Optional: used for cloud-backed discovery.",
            },
            "api_key": {
                "type": "string",
                "title": "Tuya Cloud API Key",
                "description": "Optional: used for cloud-backed discovery.",
            },
            "api_secret": {
                "type": "string",
                "title": "Tuya Cloud API Secret",
                "description": "Optional: used for cloud-backed discovery.",
            },
            "api_device_id": {
                "type": "string",
                "title": "Tuya Cloud Seed Device ID",
                "description": "Optional seed or target device id for cloud discovery.",
            },
        },
    },
    "uiSchema": {
        "host": {"placeholder": "192.168.1.50"},
        "tuya_device_id": {"placeholder": "bfxxxxxxxxxxxxxxxx"},
        "local_key": {
            "placeholder": "Local key from Tuya developer portal or TinyTuya wizard",
            "ui:widget": "password",
        },
        "alias": {"placeholder": "Desk Plug"},
        "device_type": {
            "ui:widget": "select",
            "ui:help": "Prefer the discovery-suggested value. It is inferred from Tuya category, DPS families, and product naming.",
        },
        "version": {
            "placeholder": "3.3",
            "ui:help": "If discovery reports a protocol version, keep that value unless you know the device requires a different TinyTuya version.",
        },
        "switch": {
            "placeholder": "1",
            "ui:help": "For switches, plugs, and many fans, use discovery_hints.primary_power_dp or the suggested_config.switch value from /discover.",
        },
        "fan_speed_dp": {"placeholder": "3"},
        "fan_speed_max": {"placeholder": "3"},
        "fan_oscillate_dp": {"placeholder": "5"},
        "fan_mode_dp": {"placeholder": "4"},
        "cover_control_dp": {"placeholder": "1"},
        "cover_position_dp": {"placeholder": "2"},
        "climate_target_temp_dp": {"placeholder": "16"},
        "climate_current_temp_dp": {"placeholder": "24"},
        "climate_mode_dp": {"placeholder": "4"},
        "climate_temp_scale": {"placeholder": "1 or 10"},
        "humidifier_target_humidity_dp": {"placeholder": "103"},
        "humidifier_current_humidity_dp": {"placeholder": "104"},
        "humidifier_mode_dp": {"placeholder": "2"},
        "humidifier_humidity_scale": {"placeholder": "1 or 10"},
        "purifier_speed_dp": {"placeholder": "4"},
        "purifier_speed_max": {"placeholder": "3"},
        "purifier_mode_dp": {"placeholder": "2"},
        "purifier_aqi_dp": {"placeholder": "22"},
        "purifier_aqi_scale": {"placeholder": "1 or 10"},
        "poll_interval_seconds": {"placeholder": "60"},
        "api_region": {"placeholder": "us, eu, eu-w, in, cn"},
        "api_key": {"placeholder": "Optional: used for cloud-backed discovery"},
        "api_secret": {"placeholder": "Optional cloud secret", "ui:widget": "password"},
        "api_device_id": {"placeholder": "Optional seed device id for cloud discovery"},
    },
    "discovery_defaults": {
        "enabled": True,
        "source": "discover.devices[].suggested_config",
        "apply_fields": [
            "device_type",
            "switch",
            "version",
            "fan_speed_dp",
            "fan_speed_max",
            "fan_oscillate_dp",
            "fan_mode_dp",
            "cover_control_dp",
            "cover_position_dp",
            "climate_target_temp_dp",
            "climate_current_temp_dp",
            "climate_mode_dp",
            "climate_temp_scale",
            "humidifier_target_humidity_dp",
            "humidifier_current_humidity_dp",
            "humidifier_mode_dp",
            "humidifier_humidity_scale",
            "purifier_speed_dp",
            "purifier_speed_max",
            "purifier_mode_dp",
            "purifier_aqi_dp",
            "purifier_aqi_scale",
        ],
        "identity_fields": ["host", "tuya_device_id"],
        "notes": [
            "Use host, tuya_device_id, alias, and version directly from discovered devices when present.",
            "Use suggested_config.device_type, suggested_config.switch, suggested_config.version, and any fan/cover/climate/humidifier/purifier DP overrides as setup defaults.",
            "Or use resolved_config_preview directly as a config draft and ask the user only for local_key.",
            "Use discovery_hints.supported_capabilities and discovery_hints.supported_commands to explain what the runtime inferred before the device is configured.",
        ],
        "field_mapping": {
            "host": {"from": "host"},
            "tuya_device_id": {"from": "tuya_device_id"},
            "alias": {"from": "alias"},
            "device_type": {"from": "suggested_config.device_type"},
            "switch": {"from": "suggested_config.switch"},
            "version": {"from": "suggested_config.version", "fallback": "version"},
            "fan_speed_dp": {"from": "suggested_config.fan_speed_dp"},
            "fan_speed_max": {"from": "suggested_config.fan_speed_max"},
            "fan_oscillate_dp": {"from": "suggested_config.fan_oscillate_dp"},
            "fan_mode_dp": {"from": "suggested_config.fan_mode_dp"},
            "cover_control_dp": {"from": "suggested_config.cover_control_dp"},
            "cover_position_dp": {"from": "suggested_config.cover_position_dp"},
            "climate_target_temp_dp": {
                "from": "suggested_config.climate_target_temp_dp"
            },
            "climate_current_temp_dp": {
                "from": "suggested_config.climate_current_temp_dp"
            },
            "climate_mode_dp": {"from": "suggested_config.climate_mode_dp"},
            "climate_temp_scale": {"from": "suggested_config.climate_temp_scale"},
            "humidifier_target_humidity_dp": {
                "from": "suggested_config.humidifier_target_humidity_dp"
            },
            "humidifier_current_humidity_dp": {
                "from": "suggested_config.humidifier_current_humidity_dp"
            },
            "humidifier_mode_dp": {"from": "suggested_config.humidifier_mode_dp"},
            "humidifier_humidity_scale": {
                "from": "suggested_config.humidifier_humidity_scale"
            },
            "purifier_speed_dp": {"from": "suggested_config.purifier_speed_dp"},
            "purifier_speed_max": {"from": "suggested_config.purifier_speed_max"},
            "purifier_mode_dp": {"from": "suggested_config.purifier_mode_dp"},
            "purifier_aqi_dp": {"from": "suggested_config.purifier_aqi_dp"},
            "purifier_aqi_scale": {"from": "suggested_config.purifier_aqi_scale"},
        },
        "display_fields": [
            "device_class",
            "entity_type",
            "supported_capabilities",
            "supported_commands",
            "resolved_config_preview",
            "missing_required_fields",
            "discovery_hints.primary_power_dp",
            "discovery_hints.switch_channel_count",
            "discovery_hints.classification_source",
        ],
    },
}

PLUG_FALLBACK_ENTITY: dict[str, Any] = {
    "id": "tuya-plug",
    "name": "Tuya Plug",
    "device_id": "tuya-plug",
    "device_type": "plug",
    "device_class": "outlet",
    "entity_type": "switch",
    "capabilities": PLUG_ENTITY_CAPABILITIES,
    "available_commands": [
        {"id": "refresh", "label": "Refresh", "kind": "action"},
        {"id": "turn_on", "label": "Turn On", "kind": "action"},
        {"id": "turn_off", "label": "Turn Off", "kind": "action"},
        {
            "id": "set_dp",
            "label": "Set DP",
            "kind": "action",
            "args_schema": COMMANDS["set_dp"]["args_schema"],
        },
    ],
    "dashboard": {
        "allowed_widgets": ["switch", "tile", "stat", "button"],
        "default_widget": "switch",
        "recommended_widgets": ["switch", "tile"],
    },
}

LIGHT_FALLBACK_ENTITY: dict[str, Any] = {
    "id": "tuya-light",
    "name": "Tuya Light",
    "device_id": "tuya-light",
    "device_type": "light",
    "device_class": "light",
    "entity_type": "light",
    "capabilities": LIGHT_ENTITY_CAPABILITIES,
    "available_commands": [
        {"id": "refresh", "label": "Refresh", "kind": "action"},
        {"id": "turn_on", "label": "Turn On", "kind": "action"},
        {"id": "turn_off", "label": "Turn Off", "kind": "action"},
        {
            "id": "set_brightness",
            "label": "Set Brightness",
            "kind": "action",
            "args_schema": COMMANDS["set_brightness"]["args_schema"],
        },
        {
            "id": "set_color_temp",
            "label": "Set Color Temp",
            "kind": "action",
            "args_schema": COMMANDS["set_color_temp"]["args_schema"],
        },
        {
            "id": "set_color_rgb",
            "label": "Set RGB Color",
            "kind": "action",
            "args_schema": COMMANDS["set_color_rgb"]["args_schema"],
        },
        {
            "id": "set_mode",
            "label": "Set Mode",
            "kind": "action",
            "args_schema": COMMANDS["set_mode"]["args_schema"],
        },
        {
            "id": "set_dp",
            "label": "Set DP",
            "kind": "action",
            "args_schema": COMMANDS["set_dp"]["args_schema"],
        },
    ],
    "dashboard": {
        "allowed_widgets": ["light", "tile", "button", "stat"],
        "default_widget": "light",
        "recommended_widgets": ["light", "tile"],
    },
}

FAN_FALLBACK_ENTITY: dict[str, Any] = {
    "id": "tuya-fan",
    "name": "Tuya Fan",
    "device_id": "tuya-fan",
    "device_type": "fan",
    "device_class": "fan",
    "entity_type": "fan",
    "capabilities": FAN_ENTITY_CAPABILITIES,
    "available_commands": [
        {"id": "refresh", "label": "Refresh", "kind": "action"},
        {"id": "turn_on", "label": "Turn On", "kind": "action"},
        {"id": "turn_off", "label": "Turn Off", "kind": "action"},
        {
            "id": "set_fan_speed",
            "label": "Set Fan Speed",
            "kind": "action",
            "args_schema": COMMANDS["set_fan_speed"]["args_schema"],
        },
        {
            "id": "set_oscillate",
            "label": "Set Oscillate",
            "kind": "action",
            "args_schema": COMMANDS["set_oscillate"]["args_schema"],
        },
        {
            "id": "set_mode",
            "label": "Set Mode",
            "kind": "action",
            "args_schema": COMMANDS["set_mode"]["args_schema"],
        },
        {
            "id": "set_dp",
            "label": "Set DP",
            "kind": "action",
            "args_schema": COMMANDS["set_dp"]["args_schema"],
        },
    ],
    "dashboard": {
        "allowed_widgets": ["fan", "tile", "button", "stat"],
        "default_widget": "fan",
        "recommended_widgets": ["fan", "tile"],
    },
}

COVER_FALLBACK_ENTITY: dict[str, Any] = {
    "id": "tuya-cover",
    "name": "Tuya Cover",
    "device_id": "tuya-cover",
    "device_type": "cover",
    "device_class": "cover",
    "entity_type": "cover",
    "capabilities": COVER_ENTITY_CAPABILITIES,
    "available_commands": [
        {"id": "refresh", "label": "Refresh", "kind": "action"},
        {"id": "open_cover", "label": "Open Cover", "kind": "action"},
        {"id": "close_cover", "label": "Close Cover", "kind": "action"},
        {"id": "stop_cover", "label": "Stop Cover", "kind": "action"},
        {
            "id": "set_cover_position",
            "label": "Set Cover Position",
            "kind": "action",
            "args_schema": COMMANDS["set_cover_position"]["args_schema"],
        },
        {
            "id": "set_dp",
            "label": "Set DP",
            "kind": "action",
            "args_schema": COMMANDS["set_dp"]["args_schema"],
        },
    ],
    "dashboard": {
        "allowed_widgets": ["cover", "tile", "button", "stat"],
        "default_widget": "cover",
        "recommended_widgets": ["cover", "tile"],
    },
}

CLIMATE_FALLBACK_ENTITY: dict[str, Any] = {
    "id": "tuya-climate",
    "name": "Tuya Climate",
    "device_id": "tuya-climate",
    "device_type": "climate",
    "device_class": "climate",
    "entity_type": "climate",
    "capabilities": CLIMATE_ENTITY_CAPABILITIES,
    "available_commands": [
        {"id": "refresh", "label": "Refresh", "kind": "action"},
        {"id": "turn_on", "label": "Turn On", "kind": "action"},
        {"id": "turn_off", "label": "Turn Off", "kind": "action"},
        {
            "id": "set_temperature",
            "label": "Set Temperature",
            "kind": "action",
            "args_schema": COMMANDS["set_temperature"]["args_schema"],
        },
        {
            "id": "set_mode",
            "label": "Set Mode",
            "kind": "action",
            "args_schema": COMMANDS["set_mode"]["args_schema"],
        },
        {
            "id": "set_dp",
            "label": "Set DP",
            "kind": "action",
            "args_schema": COMMANDS["set_dp"]["args_schema"],
        },
    ],
    "dashboard": {
        "allowed_widgets": ["climate", "tile", "button", "stat"],
        "default_widget": "climate",
        "recommended_widgets": ["climate", "tile"],
    },
}

HUMIDIFIER_FALLBACK_ENTITY: dict[str, Any] = {
    "id": "tuya-humidifier",
    "name": "Tuya Humidifier",
    "device_id": "tuya-humidifier",
    "device_type": "humidifier",
    "device_class": "humidifier",
    "entity_type": "humidifier",
    "capabilities": HUMIDIFIER_ENTITY_CAPABILITIES,
    "available_commands": [
        {"id": "refresh", "label": "Refresh", "kind": "action"},
        {"id": "turn_on", "label": "Turn On", "kind": "action"},
        {"id": "turn_off", "label": "Turn Off", "kind": "action"},
        {
            "id": "set_humidity",
            "label": "Set Humidity",
            "kind": "action",
            "args_schema": COMMANDS["set_humidity"]["args_schema"],
        },
        {
            "id": "set_mode",
            "label": "Set Mode",
            "kind": "action",
            "args_schema": COMMANDS["set_mode"]["args_schema"],
        },
        {
            "id": "set_dp",
            "label": "Set DP",
            "kind": "action",
            "args_schema": COMMANDS["set_dp"]["args_schema"],
        },
    ],
    "dashboard": {
        "allowed_widgets": ["humidifier", "tile", "button", "stat"],
        "default_widget": "humidifier",
        "recommended_widgets": ["humidifier", "tile"],
    },
}

AIR_PURIFIER_FALLBACK_ENTITY: dict[str, Any] = {
    "id": "tuya-air-purifier",
    "name": "Tuya Air Purifier",
    "device_id": "tuya-air-purifier",
    "device_type": "air_purifier",
    "device_class": "air_purifier",
    "entity_type": "air_purifier",
    "capabilities": AIR_PURIFIER_ENTITY_CAPABILITIES,
    "available_commands": [
        {"id": "refresh", "label": "Refresh", "kind": "action"},
        {"id": "turn_on", "label": "Turn On", "kind": "action"},
        {"id": "turn_off", "label": "Turn Off", "kind": "action"},
        {
            "id": "set_fan_speed",
            "label": "Set Fan Speed",
            "kind": "action",
            "args_schema": COMMANDS["set_fan_speed"]["args_schema"],
        },
        {
            "id": "set_mode",
            "label": "Set Mode",
            "kind": "action",
            "args_schema": COMMANDS["set_mode"]["args_schema"],
        },
        {
            "id": "set_dp",
            "label": "Set DP",
            "kind": "action",
            "args_schema": COMMANDS["set_dp"]["args_schema"],
        },
    ],
    "dashboard": {
        "allowed_widgets": ["tile", "stat", "button"],
        "default_widget": "tile",
        "recommended_widgets": ["tile", "stat"],
    },
}

GENERIC_FALLBACK_ENTITY: dict[str, Any] = {
    "id": "tuya-device",
    "name": "Tuya Device",
    "device_id": "tuya-device",
    "device_type": "device",
    "device_class": "device",
    "entity_type": "device",
    "capabilities": SWITCH_ENTITY_CAPABILITIES,
    "available_commands": [
        {"id": "refresh", "label": "Refresh", "kind": "action"},
        {"id": "turn_on", "label": "Turn On", "kind": "action"},
        {"id": "turn_off", "label": "Turn Off", "kind": "action"},
        {
            "id": "set_dp",
            "label": "Set DP",
            "kind": "action",
            "args_schema": COMMANDS["set_dp"]["args_schema"],
        },
    ],
    "dashboard": {
        "allowed_widgets": ["tile", "stat", "button"],
        "default_widget": "tile",
        "recommended_widgets": ["tile"],
    },
}
